// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCGxfrYm3gd6QsQ7tCY4yId926KkeYhWY',
    appId: '1:815477261689:web:7ba24981b8ff609d785ba8',
    messagingSenderId: '815477261689',
    projectId: 'controlx-11a84',
    authDomain: 'controlx-11a84.firebaseapp.com',
    storageBucket: 'controlx-11a84.firebasestorage.app',
    measurementId: 'G-XS5DKZENBD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0TxN8xL-KMgEJ8vFMG41J9q4AdcZLKcI',
    appId: '1:815477261689:android:6ab566cf54db51bb785ba8',
    messagingSenderId: '815477261689',
    projectId: 'controlx-11a84',
    storageBucket: 'controlx-11a84.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChDQrXzkoye-J5VZHB1JdTBA-V3d7Lgwc',
    appId: '1:815477261689:ios:721c0f136a143d9d785ba8',
    messagingSenderId: '815477261689',
    projectId: 'controlx-11a84',
    storageBucket: 'controlx-11a84.firebasestorage.app',
    iosBundleId: 'com.example.controlx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChDQrXzkoye-J5VZHB1JdTBA-V3d7Lgwc',
    appId: '1:815477261689:ios:721c0f136a143d9d785ba8',
    messagingSenderId: '815477261689',
    projectId: 'controlx-11a84',
    storageBucket: 'controlx-11a84.firebasestorage.app',
    iosBundleId: 'com.example.controlx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCGxfrYm3gd6QsQ7tCY4yId926KkeYhWY',
    appId: '1:815477261689:web:7b3442b9ce3104fa785ba8',
    messagingSenderId: '815477261689',
    projectId: 'controlx-11a84',
    authDomain: 'controlx-11a84.firebaseapp.com',
    storageBucket: 'controlx-11a84.firebasestorage.app',
    measurementId: 'G-JM381FWGLM',
  );
}
